### PR TITLE
Sort function arg names array for unsafe func output

### PR DESCRIPTION
**Pull request by JustinReiter**
Small PR to sort the function argument name vector by arg name.

Example:
image

Output:
image

### CODE REVIEW

**Review by wu-benjamin — COMMENTED** [review]
Actually looking at this, I wonder if we even want to sort alphabetically.

If the default order is the same as the function argument order, that's probably better.

I think I was thinking of the full solved Z3 model (printed for debug) for the alphabetical sort.

**Comment by JustinReiter** [comment]
There doesn't really appear to be a good way in getting all the variables in a model without significant changes (ie. storing a vector of model names & types when we build the formulas), so instead opted to parse the model string.

New output:
image

Old output:
image

**Comment by JustinReiter** [comment]
(Also reverted the change with sorting the function arguments)

**Review by wu-benjamin — APPROVED** [review]
LGTM 🚀

**Comment by AmanPal-Singh** [comment]
In the future please describe why this change is needed -- what does it accomplish in the PR description.

**Pull request merged**
